### ISSUE TITLE
Set up account functionality

### ISSUE THREAD

**Issue by stevenlaitran** [build-umass/Gifted_LLC#3]
Create functionality for logging into accounts. Whether it is through the webpage, or a specific route, we need to enable the user to log into the administrative pages of the site. Whether we want types of permissions or only a single admin level account is up for the team to decide and time constraints, however we need the beginnings of one.

- [ ] Add ability to access pages using a remotely stored key and password.
- [ ] Allow access to certain pages only if logged in

**Comment by vedantroy** [comment]
Will we be using Firebase for auth?

**Comment by stevenlaitran** [comment]
This depends on how we as a team want to implement it, we should definitely use third party apps like okta or fire base
